# This is the sample config file for the llama model.

model: 
  id: "sam2_1-hiera-base-plus"
  user_id: "phatvo"
  app_id: "segment-anything"
  model_type_id: "visual-segmenter"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "3"
  cpu_memory: "17Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "44Gi"

num_threads: 1

concepts:
  - id: none
    name: none